# Generated by Django 3.1.6 on 2021-02-02 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=256, verbose_name='URL')),
                ('name', models.TextField(blank=True, default=None, max_length=128, null=True, verbose_name='Url name')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.AlterModelOptions(
            name='webaddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webaddress',
            name='url',
        ),
        migrations.AddField(
            model_name='webaddress',
            name='address_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='addresses.address'),
            preserve_default=False,
        ),
    ]
