# Generated by Django 3.1.6 on 2021-02-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0003_auto_20210202_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.PositiveSmallIntegerField(choices=[(1, 'Http Code'), (2, 'Http Body')], default=1, verbose_name='Check type')),
                ('succes_value', models.TextField(max_length=256, verbose_name='Value awaited for success')),
                ('description', models.TextField(blank=True, default=None, max_length=256, null=True, verbose_name='Check description')),
                ('url', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address', verbose_name='Url to check')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
